# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marc's Blog
email: marcdwong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog creation in progress. I haven't decided what kind of content I will write
  about, so for now it will be random posts about random things like coding,
  gaming, movies, dogs, life, etc.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://marcdwong.com" # the base hostname & protocol for your site
twitter_username: marcdwong
github_username:  gtallest

# Build settings
markdown: kramdown
theme: minima
#markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
